language: node_js
node_js:
- 4.1.1
env:
  global:
  - GH_REF=github.com/Schibum/barcode.js.git
  - GH_BOWER=github.com/Schibum/barcode.js-bower.git
  - secure: xIHEtICHH1eXltRx4LbzBEVKOkG1ZYI8jFm0li73aXfkg6e5dx4ezELfOHk3TWGyRKQnjTH3VwCfcDxgmn6d7oB9JA0rCIa/bH+Z+Rwbadgz8Cp3mnVvfF9TTvHGzM956nUJ3pnLR3wEDOYSzHLGYRcZZ+CXV83EF3oin7Ta2X3YmfG1pjmwfpJFsWM0CpOGN/UOYqYkBbBBkZXzS1T9zswbx6XWbX/XR5GnvVxCdFnO7pEvy39xWzGa8LjWW/27pVH4EjOyX3ZXZiMu7Dmk6oPwSDnRdaKcinVOhZIEka/X3/UdBMnHbwQ65qlQaIvwmWI36boiWbp7JdNbZ3UrIT1poNFVZQ76HgbLPbCLyGK4rcWL6Urmo4zf5KdlJ21S5Hc5fKbFrH8VBFKzWaW94PcaP9+lA8Q7zYvi8/qoLa4U7XFtO0TetW4rLb0c9/6zCuTOhBxEy7lem1rhiaj3/35BhDZmpMa++aQGGvGnppl8cScOui05hLkaFo8EkVC12Ks4RVxzBAJ8UXlsfUo4ZgqXRhKr6XWXwHBZd+gW1SbK70lKguzFHeybV+SuT1R2RQk/BIpqwaydY2ziGXKTid5ThcrVdqQ/73viE42ytENx+6OCE2vkuvcVUIDLHftwnA4bXkEM5LHpWxqOa79NT8hehqj8egD9yefRHqLXyXc=
  - secure: kaUyPhgL5u4e7djiGLZxVatmm2JSH+huK/U88bwPmpGnSVj4FWAGBFp7YB/gFVwnndcE3j2SijGa1aJE2rZOvGvUmhSxdkh0psneeaUmkRMuWfDkxaG6crDzP11uvPLbEXXAp5tEBtKFtgwGgaDgVfp1n9kjv2wOhNE1F4nkOj6lCuFMLQXcJ5aUyRgfdIlSq0Pfb9Nn43+R91C75YcNiwHOQQOf4ws9jsglWdYryLHq1+s+yhGmNSpCAnjZJ3PsWTD8/2Ze7ZRitckulBTMAKN3DMToS92+cbaWmqXL0Z30GLRd9lJnElSBfTbFvphUb+mKZv6YFsASQd1mRnPz/0PmbWifS8Vj8yf6778DYbApRAdIKdQp0yUgWEzC4RPdeP77PonKHazr4Oxu5L+lsnnMgzw3fXBWsflMlHgjgsYDXfgQfuBV06XBJL17u6WHx17cv5jo1WVNW7dtJ5FQSfcAKlzXQWdr1udYvUZilGhbx3RF8hEqcLMxSdRCjH5H1xFOPyGbq81i2ZnKQk7wZBQFSsWXCe1QcnuVLn7hMXrdjn5haVVPweMZiRCuHz+PyfX50ofsklsYTvnh/ki5vKMZ4w/6ofiW+O28uy2m+DmKNn11jWkY9XRSWwiWQvwR7PcmsSkN7KTOU3Z0qFhZTyMb7DrWply1FzdJqSsijLY=
  - secure: JbeJMAGowS46BdtpOw2cvbElXb2YpHyIwk6zxKIw1GUVE3UVkSL3BD7aP0+IpLnEFOUU6+HSm0/sM5b6Wb9Fg5jqyUeCgQjMi/42mF1dQh1jBXMc/4nifWKpjaIzR/p2B8wIdbwgS0iyIp9bCHk7v/CfUyqj9kWnjtiU9mJfBbP5K74A4TRo7a4Mta5g09L8p6U6MyHjbGCBlyF6n1MWEYUjbv1V3lLQ0ZBVrh72H79L+KAr8q5xu130Yc4jJLmHiFQre4DKXa7B6jRTj1GMiSyKj+1oMAIJC7dJvsFGyWshbu6bSETwOXAfc1NRTZ4d1WqgoHNoM5dL1JQT4GRIJ2iotYhXVq1E5MIVbJoXh8/W+Puk/Nid5oC4WofjbWRfn1taWdTud2WwVZM97cuLb22wauR4Sb/GDs3IStkNSVR4Ag198iMPMu38gKcjNjG0nxzbMftV0wcE9ncUp5UOz0VjwzKQblJN0T9Z1NnAr73YgJ+Kuho1GHkShEyFRTihrgZq9azb3MtCDbCOgqGkTvWoROSF/1urpQeXN0YDNakhitgxv0NjnTPHCRlLHMROOZgP4E7x10atxNijvkXrZwShoz9XCF6neulAHpsQWaPCk15V5PaLPWns/gDQM+FNYr8VyqwAh7bICOoJoOlObwyQVIHwuu+x6mw8F1jAUBE=
  - secure: cmVHQcvve864Rml1k/wI9lAsQsSut9PocerCIP2VwRJ8Y0fFtdsb6CdsQNf2rqnZ9cS5wKkXU1yCjuz8zs8zD5UX/VSW+cpkBc/TIHv1fTk+cFe8Z0XxmVcx4oiXHZhxuAo2Uefc7hjW4uuo7nYjJgf0WCxJdMCniwO4qfq8vNjKMWLmP6WOWkVHawWQPh0oWy3FD99kgG3WlDXFC8DBJmo+B4UkRR8YnlydiXpgVj67L0YDVp0rYfaICPQJNBXZkHxxQMZybjysjBBRghJDp/8fLtk06jzNogCUlzsRteSTQKMDOej9h2h4NGtkn2JTWHeHrCKFc699oV8jm4GLr9waJC4yj5oXOcYftJAkGM9qJboUPFWzyK0NXH3gL92iXVh+guhazpFsBpZOLUTi/5/i4scW9keLElrHdoP8XZqgjW0dwwIGgM7hOePSSc+2aHlU0JxqKt4coySpS4EiNg37r5wsQuY2jy/vK57HFShKJzsgrX7lOMF9bwoeGu6jsMdP3XVn7Czn1hboNXeUwFmoSmlKm1QtXMT3oNoG4MgFeY3QDLUcGqbVLx4TznK93NiRQgy8gRHWyvt5X3NjBuqal7EVP8IYgEieDXn+8qeW+1lwTZ4oDrNhBJWVRL8yaqvGWLCl1VZpawQq3dRdlG3abjmVUFjG8FWbO5A+lRc=
addons:
  sauce_connect: true
  firefox: "latest"
cache:
  directories:
  - node_modules
install:
- npm config set spin false
- npm config set loglevel http
- npm install
before_script:
- npm install -g gulp
- "export CHROME_BIN=chromium-browser"
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start
script: gulp
deploy:
- provider: script
  skip_cleanup: true
  script: scripts/deploy.sh
  on:
    tags: true
- provider: script
  script: scripts/update-page.sh
  skip_cleanup: true
  on:
    branch: master
